// Relação oficial das lojas (planilha 27/11). Edite nomes aqui se necessário.
export const LOJAS = [
  { cod: "FR02", nome: "JARDIM NOVA ESPERANÇA" },
  { cod: "FR03", nome: "ABADIA (PARQUE IZABEL)" },
  { cod: "FR04", nome: "VEIGA JARDIM" },
  { cod: "FR06", nome: "MORADA DOS PASSAROS" },
  { cod: "FR08", nome: "MADRE GERMANA II" },
  { cod: "FR12", nome: "GOIANIRA" },
  { cod: "FR16", nome: "BALNEARIO MEIA PONTE" },
  { cod: "FR19", nome: "CRISTINA" },
  { cod: "FR20", nome: "GOIANIA VIVA" },
  { cod: "FR21", nome: "IBIRAPUERA" },
  { cod: "FR22", nome: "TRINDADE (VILA PAI ETERNO)" },
  { cod: "FR23", nome: "INHUMAS (CENTRO)" },
  { cod: "FR25", nome: "VILA ALZIRA" },
  { cod: "FR28", nome: "NOVO HORIZONTE" },
  { cod: "FR29", nome: "BELA VISTA DE GOIAS" },
  { cod: "FR31", nome: "INHUMAS (SOLAR PARQUE)" },
  { cod: "FR32", nome: "RETIRO DO BOSQUE" },
  { cod: "FR35", nome: "CURITIBA 4 (JC-1)" },
  { cod: "FR36", nome: "NOVA VILA" },
  { cod: "FR38", nome: "URIAS MAGALHÃES" },
  { cod: "FR40", nome: "PARQUE DAS NAÇÕES" },
  { cod: "FR42", nome: "INDIARA" },
  { cod: "FR43", nome: "BH (MG)" },
  { cod: "FR44", nome: "SANTO HILARIO" },
  { cod: "FR45", nome: "RIACHO FUNDO (DF)" },
  { cod: "FR49", nome: "ELI FORTE" },
  { cod: "FR50", nome: "SILVANIA" },
  { cod: "FR51", nome: "VILA REDENÇÃO" },
  { cod: "FR52", nome: "VICENTE PIRES (DF)" },
  { cod: "FR54", nome: "GUANABARA III" },
  { cod: "FR55", nome: "JARDIM AMERICA (T-9)" },
  { cod: "FR56", nome: "JARDIM AMERICA (C-1)" },
  { cod: "FR57", nome: "ANAPOLIS (VILA JAYARA)" },
  { cod: "FR58", nome: "VERA CRUZ (CENTRO APARECIDA)" },
  { cod: "FR59", nome: "SETOR AEROPORTO (PRACA DO AVIAO)" },
  { cod: "FR60", nome: "SANTA GENOVEVA" },
  { cod: "FR62", nome: "CARDOSO" },
  { cod: "FR64", nome: "JARDIM BELA VISTA" },
  { cod: "FR65", nome: "PALMAS (Q 804 / TO)" },
  { cod: "FR66", nome: "BAIRRO GOIA" },
  { cod: "FR67", nome: "CIDADE SATELITE SÃO LUIZ" },
  { cod: "FR68", nome: "CAMPINAS" },
  { cod: "FR70", nome: "HIDROLANDIA" },
  { cod: "FR71", nome: "PERIM (GO)" },
  { cod: "FR72", nome: "SÃO LUIS MONTES BELOS" },
  { cod: "FR73", nome: "CIDADE NOVA (AV TRANSAMAZONICA) (PA)" },
  { cod: "FR76", nome: "CIDADE VERA CRUZ" },
  { cod: "FR78", nome: "SITIO SANTA LUZIA" },
  { cod: "FR80", nome: "VIANOPOLIS" },
  { cod: "FR81", nome: "ARAGOIANIA" },
  { cod: "FR82", nome: "MARECHAL RONDON" },
  { cod: "FR85", nome: "JARDIM PLANALTO" },
  { cod: "FR87", nome: "IPORA (CENTRO)" },
  { cod: "FR88", nome: "LESTE UNIVERSITARIO" },
  { cod: "FR90", nome: "SENADOR CANEDO (CENTRO)" },
  { cod: "FR91", nome: "GUARAÍ (TO)" },
  { cod: "FR93", nome: "JARAGUÁ" },
  { cod: "FR95", nome: "CONJ VERA CRUZ" },
  { cod: "FR96", nome: "DOM FERNANDO" },
  { cod: "FR97", nome: "VILA PEDROSO" },
  { cod: "FR98", nome: "MORRINHOS" },
  { cod: "FR99", nome: "PRAÇA DA BIBLIA" },
  { cod: "FR100", nome: "JARDIM ATLANTICO" },
  { cod: "FR101", nome: "GOIANESIA" },
  { cod: "FR103", nome: "JARDIM CURITIBA (JC-10)" },
  { cod: "FR104", nome: "CANARANA (MT)" },
  { cod: "FR105", nome: "BARRA DO GARÇAS (MT)" },
  { cod: "FR106", nome: "PARQUE TRINDADE (PARQUE ATHENEU)" },
  { cod: "FR107", nome: "ARAGUAINA VILA ROSARIO (TO)" },
  { cod: "FR109", nome: "RIO VERDE (GO)" },
  { cod: "FR110", nome: "SENADOR CANEDO (MORADA DO MORRO)" },
  { cod: "FR111", nome: "RUBIATABA" },
  { cod: "FR113", nome: "SÃO MIGUEL DO ARAGUAIA" },
  { cod: "FR114", nome: "ANAPOLIS (PORTAL DO CERRADO)" },
  { cod: "FR115", nome: "JOAO PESSOA (PB)" },
  { cod: "FR116", nome: "VILA BRASILIA (AV RUDÁ)" },
  { cod: "FR117", nome: "QUARTA RADIAL (SETOR BELA VISTA)" },
  { cod: "FR118", nome: "MINEIROS (LOT CAMBAUVA)" },
  { cod: "FR121", nome: "ARAGARÇAS (GO)" },
  { cod: "FR122", nome: "JARDIM AMERICA (C-104)" },
  { cod: "FR123", nome: "MONTIVIDIU" },
  { cod: "FR124", nome: "PALMEIRAS" },
  { cod: "FR125", nome: "NOVA MARABA (FOLHA 28) (PA)" },
  { cod: "FR126", nome: "IMPERATRIZ (MA)" },
  { cod: "FR127", nome: "JARDIM TROPICAL (LAGO DOS PATOS)" },
  { cod: "FR128", nome: "ITAPURANGA" },
  { cod: "FR129", nome: "FAIÇALVILLE (AVENIDA RIO VERDE)" },
  { cod: "FR130", nome: "JOAO PINHEIRO (MG)" },
  { cod: "FR132", nome: "ANAPOLIS (JAMEL CECILIO)" },
  { cod: "FR133", nome: "SANTA LUZIA (MG)" },
  { cod: "FR135", nome: "VILA REGINA" },
  { cod: "FR136", nome: "SÃO FELIX (PA)" },
  { cod: "FR137", nome: "BAIRRO FLORESTA" },
  { cod: "FR138", nome: "ORIZONA (GO)" },
  { cod: "FR139", nome: "TRINDADE (VILA JOAO BRAZ)" },
  { cod: "FR140", nome: "CONJ RIVIERA" },
  { cod: "FR141", nome: "TUCURUI (PA)" },
  { cod: "FR142", nome: "NOVO REPARTIMENTO (PA)" },
  { cod: "FR144", nome: "VARGINHA (MG)" },
  { cod: "FR145", nome: "AGUA BOA (MT)" },
  { cod: "FR146", nome: "CIDADE DE GOIAS" },
  { cod: "FR148", nome: "PORANGATU -CENTRO (GO)" },
  { cod: "FR149", nome: "PARQUE AMAZONIA" },
  { cod: "FR150", nome: "ITUMBIARA" },
  { cod: "FR151", nome: "EDEIA (GO)" },
  { cod: "FR152", nome: "PRIMAVERA DO LESTE (MT)" },
  { cod: "FR153", nome: "MANGABEIRA (PB)" },
  { cod: "FR154", nome: "PARAUAPEBAS (CIDADE JARDIM ) PA" },
  { cod: "FR155", nome: "SANTAREM (MZ SANTA CLARA) (PA)" },
  { cod: "FR156", nome: "PIRACANJUBA (GO)" },
  { cod: "FR157", nome: "NEROPOLIS" },
  { cod: "FR158", nome: "CATALAO (GO)" },
  { cod: "FR159", nome: "ACREUNA (GO)" },
  { cod: "FR160", nome: "CIDADE JARDIM (GO)" },
  { cod: "FR161", nome: "VILA MAUÁ (BANDEIRAS)" },
  { cod: "FR162", nome: "DOURADOS (MS)" },
  { cod: "FR163", nome: "CANAA DOS CARAJAS (PA)" },
  { cod: "FR164", nome: "MORADA DO SOL (AV MANGALO)" },
  { cod: "FR165", nome: "GUAPO (GO)" },
  { cod: "FR167", nome: "FORMOSA (GO)" },
  { cod: "FR169", nome: "JOÃO PESSOA (BESSA-PB)" },
  { cod: "FR170", nome: "SENADOR CANEDO (JARDIM DAS OLIVEIRAS)" },
  { cod: "FR171", nome: "VILA BRASILIA (AV SÃO PAULO)" },
  { cod: "FR172", nome: "ANICUNS (GO)" },
  { cod: "FR173", nome: "JARDIM AMERICA (C-205)" },
  { cod: "FR174", nome: "NOVA MARABA (FOLHA 21) (PA)" },
  { cod: "FR175", nome: "CRISTALINA (GO)" },
  { cod: "FR176", nome: "GOIATUBA (GO)" },
  { cod: "FR177", nome: "PETROLINA (PE)" },
  { cod: "FR178", nome: "SÃO DOMINGOS DO ARAGUAIA (PA)" },
  { cod: "FR179", nome: "REDENÇÃO (PA)" },
  { cod: "FR180", nome: "CASSINO (RS)" },
  { cod: "FR181", nome: "BOM JESUS (GO)" },
  { cod: "FR182", nome: "PONTALINA (GO)" },
  { cod: "FR183", nome: "SETOR COIMBRA (GO)" },
  { cod: "FR184", nome: "SENADOR CANEDO (PEDRO MIRANDA)" },
  { cod: "FR185", nome: "CAICÓ (RN)" },
  { cod: "FR186", nome: "ALVORADA (TO)" },
  { cod: "FR187", nome: "JATAI (GO)" },
  { cod: "FR189", nome: "PARAUAPEBAS (BETANIA) PA" },
  { cod: "FR190", nome: "XINGUARA (PA)" },
  { cod: "FR191", nome: "SANTAREM (FL CURUA UNA) (PA)" },
  { cod: "FR192", nome: "IPORA (JD NOVO HORIZONTE)" },
  { cod: "FR193", nome: "MOINHO DOS VENTOS (GO)" },
  { cod: "FR194", nome: "SAO JUDAS TADEU" },
  { cod: "FR195", nome: "RECIFE (PE)" },
  { cod: "FR197", nome: "TANGARA DA SERRA (MT) MATRIZ" },
  { cod: "FR198", nome: "COLINAS DO TOCANTINS (TO)" },
  { cod: "FR199", nome: "PRIMAVERA DO LESTE -FILIAL (MT)" },
  { cod: "FR200", nome: "CENTER MINEIROS (SETOR IORIS)" },
  { cod: "FR201", nome: "SENADOR CANEDO (RES. BOA VISTA)" },
  { cod: "FR202", nome: "MAYSA (PARQUE BURITI)" },
  { cod: "FR203", nome: "VILA ITATIAIA" },
  { cod: "FR204", nome: "JARDIM NOVO MUNDO" },
  { cod: "FR205", nome: "TANGARA DA SERRA (MT) FILIAL" },
];